### ISSUE TITLE
How to get my Playnite to look like your screenshot?

### ISSUE THREAD

**Issue by Garydunlop00** [Jhanlon95/Seaside#1]
Hey man i was wondering how to get my playnite to look like your screenshot?

when i install your theme mine looks different even though i have all the same addons active.
![MyIdeal](https://user-images.githubusercontent.com/42975286/193918150-f8717c47-1cf5-4ebb-8a67-ac31a62a99eb.jpg)
![Playnite DesktopApp_iU5mdim4rP](https://user-images.githubusercontent.com/42975286/193918210-740dd5f5-ea9c-4c58-9d9d-f3bba2744d0b.png)

**Comment by Garydunlop00** [comment]
![Playnite DesktopApp_n4xX1GGj7P](https://user-images.githubusercontent.com/42975286/193918377-de10a03e-ee9b-4922-8e88-ce38bcb28aaf.png)

Figured out how to move the sidebar

**Comment by Jhanlon95** [comment]
Hi, this is what I have for my settings, I hope this helps

### Details view
![image](https://user-images.githubusercontent.com/11045596/194120882-8cc1e8de-0e88-4a20-8649-ba1d56979a33.png)


### Layout
![image](https://user-images.githubusercontent.com/11045596/194120950-ca4da8c5-e496-4879-bad8-d31f3d675905.png)

### Top Panel
![image](https://user-images.githubusercontent.com/11045596/194121007-81ae3a50-4314-4905-a0d9-2017f8b70dc5.png)
