### ISSUE TITLE
[bug] [grid view] Library banners disappeared from tiles in 1.6.9

### ISSUE THREAD

**Issue by hellridergit** [Jhanlon95/Seaside#3]
Hello,
just updated from 1.6.8 to 1.6.9 and noticed the library banners on top of each tile in the grid view, are gone.

These 4 games are on 4 different platforms, with 1.6.8 it was evident, now not so much.
![image](https://user-images.githubusercontent.com/10494075/213865365-cad8e829-e739-4436-82a2-b25235653012.png)

Playnite 10.9 portable, on windows 10.

**Comment by Jhanlon95** [comment]
Hi, thanks for raising this. I have checked on my version of Playnite and they look to be working as expected. I don't know what library "Beat the Devil" is on so I couldn't check on that one. Have these been imported manually, or were they imported through their respective library add-ons (GOG Library, Epic, Ubisoft Connect, etc)?

![image](https://user-images.githubusercontent.com/11045596/213869155-7823e1f2-a819-41d7-97c9-e03ac6d3c558.png)



Could you check that you have ThemeModifier add-on installed and if so can you check that you have the "Show game platforms and library banners on covers" enabled?

**Comment by hellridergit** [comment]
Beat the Devil is steam app ID 2166260.
All the games I showed before were synced automatically.

I didn't previously have the ThemeModifier, but now I do, and yes, the "Show game platforms and library banners on covers" is enabled.

The issue remains.

**Comment by Jhanlon95** [comment]
Do you have the ThemeExtra's add-on? The change I made was that the banners required that add-on as it greatly simplified how they were within defined within the xaml code

**Comment by hellridergit** [comment]
Didn't have it, but installed it just now, it seems to have resolved the problem.

I don't believe I've seen any info regarding ThemeModifier or ThemeExtras when installing Seaside directly from Playnite.
Could add it to the description perhaps.

Thanks, resolved.

**Comment by Jhanlon95** [comment]
You're right, apologies for the confusion. I will add information about it so it appears in the Playnite add-on browser. I'm glad that fixed it for you though :)
