### ISSUE TITLE
Add support for Steam News and Players viewer extension

### ISSUE THREAD

**Issue by Yuzuriha-San** [Jhanlon95/Seaside#6]
The [extension ](https://github.com/darklinkpower/PlayniteExtensionsCollection/wiki/News-Viewer)displays the number of players that are currently in-game, even for non-steam games.

![librewolf_jbRcuKOiFz](https://github.com/Jhanlon95/Seaside/assets/97923430/922af6fd-675d-428d-8e10-c72926f51ca4)

**Comment by Jhanlon95** [comment]
Should be fixed as part of 6759dff
