### ISSUE TITLE
Can't turn off platform banners

### ISSUE THREAD

**Issue by SneakyLeif** [Jhanlon95/Seaside#8]
Hello, this is by far my favorite theme! The only issue I've found is when unchecking "Show game platforms and library banners on covers" in the ThemeExtras settings, it still shows. The toggle works correctly on other ThemeExtras supported themes.

Thank you, let me know if you can't replicate it or need any more info.

**Comment by Jhanlon95** [comment]
Hi! Thank you for the kind words. I was trying to find the setting that you mentioned but I can't see it when I check ThemeExtra's settings I don't see a checkbox for "Show game platforms and library banners on covers", could you send me a screenshot of the setting that you're seeing?

**Comment by SneakyLeif** [comment]
Sorry, I forgot that the setting is under ThemeModifier's "Edit constants" tab. ThemeExtras is just required for the banners. Disabling ThemeExtras is a temporary fix for this problem.

Here's a screenshot:
![image](https://github.com/user-attachments/assets/bccc1a86-e792-460c-95fa-29ffd694c76d)

The setting is unchecked, but the banners are still there, resulting in duplicate platforms on a lot of my covers that already have them.

Thanks so much for the quick reply, you're awesome!! :)

**Comment by Jhanlon95** [comment]
Should be fixed as part of 6759dff
